server:
  port: 8383
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/api/checkout/**
          filters:
            - AddRequestHeader=x-request-from,gateway
        
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
          filters:
            - AddRequestHeader=x-request-from,gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
